version: '3.4'

services:
  app:
    build: .
    hostname: app
    container_name: app
    networks:
      - main
    command: sh -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && python -m uvicorn config.asgi:application --workers 2 --host 0.0.0.0 --port 8000 --reload
      "
#      && python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker --workers 2 --bind 0.0.0.0:8000 --reload
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app
      - ./static:/opt/app/static

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    networks:
      - main
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./static:/var/www/app/static
      - ./nginx.dev.conf:/etc/nginx/nginx.conf


networks:
  main:
